const colors = {
  light: {
    text: "#ffffff",
    tint: "#a855f7",
    background: "#000000",
    foreground: "#ffffff",
    card: "#1a1a1a",
    cardForeground: "#ffffff",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#1e1e1e",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#888888",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    surface: "#111111",
  },

  dark: {
    text: "#ffffff",
    tint: "#a855f7",
    background: "#000000",
    foreground: "#ffffff",
    card: "#1a1a1a",
    cardForeground: "#ffffff",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#1e1e1e",
    secondaryForeground: "#ffffff",
    muted: "#1e1e1e",
    mutedForeground: "#888888",
    accent: "#a855f7",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    surface: "#111111",
  },

  radius: 12,
};

export default colors;
